from unittest import TestCase
from Parsers.TuiParser import TuiParser


class TestTuiParser(TestCase):
    def test_get_data_returns_some_data_after_calling_parse_data_on_content(self):
        parser = TuiParser('some_date')
        json_string = '{"count":3671,"rows":[' \
                      '{"id":"255430","airport_to_from":"WAW","airport_to_to":"HRG","airport_from_from":"HRG","airport_from_to":"WAW","code_carrier":"LLP","code_carrier_back":"LLP","dt_from":"2016-01-14","dt_to":"2016-01-21","price":"597","price_currency":"PLN","free_seats":"4","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-09 23:15:12","flight_number":"","flight_number_back":"","price_nb":"797","free_seats_nb":"4","free_seats_max":"12","flight_class":"Y","current_price":"597","airport_from_name":"Warszawa","airport_to_name":"Hurghada","dt_from_day":"5","dt_from_to":"5","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":"188","region_name_from":"Beskid \u015al\u0105ski","id_country_to":"9","country_name_to":"Egipt","id_region_to":"16","region_name_to":"Hurghada"}' \
                      ',{"id":"242375","airport_to_from":"WAW","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"WAW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-14","dt_to":"2016-05-21","price":"597","price_currency":"PLN","free_seats":"6","promotion_code":"SPEC","dt_length":"7","last_update":"2015-12-17 23:15:49","flight_number":"","flight_number_back":"","price_nb":"647","free_seats_nb":"9","free_seats_max":"24","flight_class":"Y","current_price":"597","airport_from_name":"Warszawa","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"7","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":"188","region_name_from":"Beskid \u015al\u0105ski","id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"241416","airport_to_from":"KTW","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"KTW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-14","dt_to":"2016-05-21","price":"597","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"7","last_update":"2015-11-18 23:15:55","flight_number":"","flight_number_back":"","price_nb":"597","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"597","airport_from_name":"Katowice","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"7","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"243723","airport_to_from":"KTW","airport_to_to":"VAR","airport_from_from":"VAR","airport_from_to":"KTW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-19","dt_to":"2016-05-26","price":"597","price_currency":"PLN","free_seats":"1","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-07 23:14:40","flight_number":"","flight_number_back":"","price_nb":"647","free_seats_nb":"9","free_seats_max":"19","flight_class":"Y","current_price":"597","airport_from_name":"Katowice","airport_to_name":"Warna","dt_from_day":"5","dt_from_to":"5","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"115","region_name_to":"Warna"}' \
                      ',{"id":"240945","airport_to_from":"KTW","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"KTW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-21","dt_to":"2016-05-28","price":"597","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-09 23:14:35","flight_number":"","flight_number_back":"","price_nb":"597","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"597","airport_from_name":"Katowice","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"7","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"241527","airport_to_from":"KRK","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"KRK","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-24","dt_to":"2016-05-31","price":"597","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"7","last_update":"2015-10-23 23:14:16","flight_number":"","flight_number_back":"","price_nb":"597","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"597","airport_from_name":"Krak\u00f3w","airport_to_name":"Burgas","dt_from_day":"3","dt_from_to":"3","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"240948","airport_to_from":"KTW","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"KTW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-24","dt_to":"2016-05-31","price":"597","price_currency":"PLN","free_seats":"3","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-09 23:14:35","flight_number":"","flight_number_back":"","price_nb":"647","free_seats_nb":"9","free_seats_max":"21","flight_class":"Y","current_price":"597","airport_from_name":"Katowice","airport_to_name":"Burgas","dt_from_day":"3","dt_from_to":"3","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"243694","airport_to_from":"KTW","airport_to_to":"VAR","airport_from_from":"VAR","airport_from_to":"KTW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-26","dt_to":"2016-06-02","price":"597","price_currency":"PLN","free_seats":"8","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-08 23:14:47","flight_number":"","flight_number_back":"","price_nb":"647","free_seats_nb":"9","free_seats_max":"26","flight_class":"Y","current_price":"597","airport_from_name":"Katowice","airport_to_name":"Warna","dt_from_day":"5","dt_from_to":"5","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"115","region_name_to":"Warna"}' \
                      ',{"id":"248439","airport_to_from":"WAW","airport_to_to":"VAR","airport_from_from":"VAR","airport_from_to":"WAW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-26","dt_to":"2016-06-02","price":"647","price_currency":"PLN","free_seats":"7","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-07 23:15:00","flight_number":"","flight_number_back":"","price_nb":"667","free_seats_nb":"9","free_seats_max":"25","flight_class":"Y","current_price":"647","airport_from_name":"Warszawa","airport_to_name":"Warna","dt_from_day":"5","dt_from_to":"5","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":"188","region_name_from":"Beskid \u015al\u0105ski","id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"115","region_name_to":"Warna"}' \
                      ',{"id":"241658","airport_to_from":"POZ","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"POZ","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-28","dt_to":"2016-06-03","price":"647","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"6","last_update":"2016-01-09 23:14:50","flight_number":"","flight_number_back":"","price_nb":"647","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"647","airport_from_name":"Pozna\u0144","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"6","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"248441","airport_to_from":"WAW","airport_to_to":"VAR","airport_from_from":"VAR","airport_from_to":"WAW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-19","dt_to":"2016-05-26","price":"667","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-07 23:15:00","flight_number":"","flight_number_back":"","price_nb":"667","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"667","airport_from_name":"Warszawa","airport_to_name":"Warna","dt_from_day":"5","dt_from_to":"5","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":"188","region_name_from":"Beskid \u015al\u0105ski","id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"115","region_name_to":"Warna"}' \
                      ',{"id":"221246","airport_to_from":"KTW","airport_to_to":"TFS","airport_from_from":"TFS","airport_from_to":"KTW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-01-14","dt_to":"2016-01-21","price":"697","price_currency":"PLN","free_seats":"2","promotion_code":"SPEC","dt_length":"7","last_update":"2016-01-05 23:14:47","flight_number":"","flight_number_back":"","price_nb":"697","free_seats_nb":"2","free_seats_max":"13","flight_class":"Y","current_price":"697","airport_from_name":"Katowice","airport_to_name":"Teneryfa","dt_from_day":"5","dt_from_to":"5","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"7","country_name_to":"Wyspy Kanaryjskie","id_region_to":"11","region_name_to":"Teneryfa"}' \
                      ',{"id":"242380","airport_to_from":"WAW","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"WAW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-21","dt_to":"2016-05-29","price":"697","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"8","last_update":"2015-11-25 23:15:39","flight_number":"","flight_number_back":"","price_nb":"697","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"697","airport_from_name":"Warszawa","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"1","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":"188","region_name_from":"Beskid \u015al\u0105ski","id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"242379","airport_to_from":"WAW","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"WAW","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-21","dt_to":"2016-05-28","price":"697","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"7","last_update":"2015-11-25 23:15:39","flight_number":"","flight_number_back":"","price_nb":"697","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"697","airport_from_name":"Warszawa","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"7","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":"188","region_name_from":"Beskid \u015al\u0105ski","id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}' \
                      ',{"id":"241657","airport_to_from":"POZ","airport_to_to":"BOJ","airport_from_from":"BOJ","airport_from_to":"POZ","code_carrier":"ENT","code_carrier_back":"ENT","dt_from":"2016-05-21","dt_to":"2016-05-28","price":"697","price_currency":"PLN","free_seats":"9","promotion_code":"SPEC","dt_length":"7","last_update":"2015-12-02 23:15:36","flight_number":"","flight_number_back":"","price_nb":"697","free_seats_nb":"9","free_seats_max":"36","flight_class":"Y","current_price":"697","airport_from_name":"Pozna\u0144","airport_to_name":"Burgas","dt_from_day":"7","dt_from_to":"7","adults_count":"1","children_count":"0","infants_count":"0","id_country_from":"20","country_name_from":"Polska","id_region_from":null,"region_name_from":null,"id_country_to":"35","country_name_to":"Bu\u0142garia","id_region_to":"193","region_name_to":"Burgas"}]}'

        parser.parse_data(json_string)
        data = parser.get_data()

        self.assertEqual(15, len(data.get_rows()))

    def test_has_more_data_returns_true_after_calling_parse_data_on_content_with_json_param_count_greater_than_page_number(
            self):
        json_string = '{"count":4,"rows":[]}'
        parser = TuiParser('some_date')

        parser.parse_data(json_string)

        self.assertTrue(parser.has_more_data())

    def test_has_more_data_returns_false_after_calling_parse_data_on_content_with_json_param_count_equal_page_number(
            self):
        json_string = '{"count":1,"rows":[]}'
        parser = TuiParser('some_date')

        parser.parse_data(json_string)

        self.assertFalse(parser.has_more_data())
